spring:

  datasource:
    url: jdbc:mysql://localhost:3306/playground?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /templates
      suffix: .html



#  web:
#    resources:
#      static-locations: file:e:/playgroundpicture

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:E:/playgroundpicture

# 映射端口
server:
  port: 8080

